server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: '&cYeet and delete'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: a55dbbd5-16d2-497b-a167-0eb198770fe7
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: '&cSurvival Creative and Minigames!'
    address: localhost:25555
    restricted: false
  survival:
    motd: '&cWhy would you join this?'
    address: localhost:25556
    restricted: false
  creative:
    motd: '&cWhy would you join this?'
    address: localhost:25557
    restricted: false
  bedwars:
    motd: '&cWhy would you join this?'
    address: localhost:25558
    restricted: false
  pvp:
    motd: '&cWhy would you join this?'
    address: localhost:25559
    restricted: false
  spleef:
    motd: '&cWhy would you join this?'
    address: localhost:25560
    restricted: false
  elytra:
    motd: '&cWhy would you join this?'
    address: localhost:25561
    restricted: false
  blockfall:
    motd: '&cWhy would you join this?'
    address: localhost:25562
    restricted: false
  withered:
    motd: '&cWhy would you join this?'
    address: localhost:25563
    restricted: false
  skywars:
    motd: '&cWhy would you join this?'
    address: localhost:25564
    restricted: false
